
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSTR = 32;
  public static final int IDENTIFICADOR = 42;
  public static final int LLAVE2 = 15;
  public static final int APPEND = 64;
  public static final int LLAVE1 = 14;
  public static final int BREAKR = 39;
  public static final int MASP = 54;
  public static final int TOSTRING = 72;
  public static final int POTENCIA = 59;
  public static final int VERDADERO = 29;
  public static final int MAYOR = 8;
  public static final int CASTEO = 60;
  public static final int FALSO = 30;
  public static final int POR = 4;
  public static final int STRUCT = 67;
  public static final int CORCHETE2 = 20;
  public static final int CORCHETE1 = 19;
  public static final int NOT = 21;
  public static final int COMENTARIO = 46;
  public static final int MATCH = 35;
  public static final int NOP = 53;
  public static final int STRINGT = 26;
  public static final int BOOLT = 27;
  public static final int INTT = 25;
  public static final int PRINTR = 41;
  public static final int COMENTARIO_MULTILINEA = 47;
  public static final int CONTINUER = 40;
  public static final int DIVIDIDO = 5;
  public static final int COMA = 18;
  public static final int ENTERO = 44;
  public static final int MODULO = 6;
  public static final int CHART = 28;
  public static final int VARR = 31;
  public static final int IGUAL = 7;
  public static final int EQUAL = 49;
  public static final int DECIMAL = 43;
  public static final int FIND = 73;
  public static final int DOSPUNTOS = 17;
  public static final int PUNTOYCOMA = 16;
  public static final int MAY = 57;
  public static final int VOID = 66;
  public static final int RETURN = 69;
  public static final int MENOS = 2;
  public static final int MENOR = 9;
  public static final int MAS = 3;
  public static final int FORR = 37;
  public static final int DOR = 38;
  public static final int LENGTH = 71;
  public static final int MENOSP = 55;
  public static final int EOF = 0;
  public static final int PUNTO = 63;
  public static final int DIF = 50;
  public static final int CARACTER = 58;
  public static final int MENORIGUAL = 52;
  public static final int OR = 23;
  public static final int ELSER = 34;
  public static final int error = 1;
  public static final int START = 68;
  public static final int LIST = 62;
  public static final int GUIONBAJO = 11;
  public static final int UMENOS = 48;
  public static final int DOUBLET = 24;
  public static final int WHILER = 36;
  public static final int CADENA = 45;
  public static final int MAYORIGUAL = 51;
  public static final int NEW = 61;
  public static final int IFR = 33;
  public static final int ROUND = 70;
  public static final int PARENTESIS2 = 13;
  public static final int PARENTESIS1 = 12;
  public static final int AND = 22;
  public static final int MEN = 56;
  public static final int REMOVE = 65;
  public static final int XOR = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MENOS",
  "MAS",
  "POR",
  "DIVIDIDO",
  "MODULO",
  "IGUAL",
  "MAYOR",
  "MENOR",
  "XOR",
  "GUIONBAJO",
  "PARENTESIS1",
  "PARENTESIS2",
  "LLAVE1",
  "LLAVE2",
  "PUNTOYCOMA",
  "DOSPUNTOS",
  "COMA",
  "CORCHETE1",
  "CORCHETE2",
  "NOT",
  "AND",
  "OR",
  "DOUBLET",
  "INTT",
  "STRINGT",
  "BOOLT",
  "CHART",
  "VERDADERO",
  "FALSO",
  "VARR",
  "CONSTR",
  "IFR",
  "ELSER",
  "MATCH",
  "WHILER",
  "FORR",
  "DOR",
  "BREAKR",
  "CONTINUER",
  "PRINTR",
  "IDENTIFICADOR",
  "DECIMAL",
  "ENTERO",
  "CADENA",
  "COMENTARIO",
  "COMENTARIO_MULTILINEA",
  "UMENOS",
  "EQUAL",
  "DIF",
  "MAYORIGUAL",
  "MENORIGUAL",
  "NOP",
  "MASP",
  "MENOSP",
  "MEN",
  "MAY",
  "CARACTER",
  "POTENCIA",
  "CASTEO",
  "NEW",
  "LIST",
  "PUNTO",
  "APPEND",
  "REMOVE",
  "VOID",
  "STRUCT",
  "START",
  "RETURN",
  "ROUND",
  "LENGTH",
  "TOSTRING",
  "FIND"
  };
}

